# **Collaborative Recommendation System**

## **Importing Necessary Libraries**

In [36]:
import numpy as np
import pandas as pd

## **Uploading Dataset**

In [43]:
import pandas as pd
df = pd.read_csv('/content/Assignment_02.csv')
df1 = df.copy()
df.head()

Customer  r1  r2  r3  r4   r5
0       C1   5   3   4   4  NaN
1       C2   3   1   2   3  3.0
2       C3   4   3   4   3  5.0
3       C4   3   3   1   5  4.0
4       C5   1   5   5   2  1.0

In [44]:
newdf = df.drop(['r5'], axis=1)
newdf.head()

Customer  r1  r2  r3  r4
0       C1   5   3   4   4
1       C2   3   1   2   3
2       C3   4   3   4   3
3       C4   3   3   1   5
4       C5   1   5   5   2

## **Cosine Similarity**

In [45]:
def cosine_similarity(a, b):
  dot_product = np.dot(a, b)
  norm_a = np.linalg.norm(a)
  norm_b = np.linalg.norm(b)
  if norm_a == 0 or norm_b == 0:
    return 0
  return dot_product / (norm_a * norm_b)

## **Similarity Matrix**

In [46]:
num_users = len(newdf)
similarity_matrix = np.zeros((num_users, num_users))

for i in range(len(newdf)):
    for j in range(0, num_users):
        X1 = newdf.iloc[i, 1:].values
        X2 = newdf.iloc[j, 1:].values
        similarity_matrix[i, j] = cosine_similarity(X1, X2)
        similarity_matrix[j, i] = similarity_matrix[i, j]

# Print similarity matrix
print("Similarity Matrix:")
print(similarity_matrix)

Similarity Matrix:
[[1.         0.9753213  0.99224264 0.89072354 0.79668736]
 [0.9753213  1.         0.94362852 0.91160719 0.67478587]
 [0.99224264 0.94362852 1.         0.85280287 0.85811633]
 [0.89072354 0.91160719 0.85280287 1.         0.67082039]
 [0.79668736 0.67478587 0.85811633 0.67082039 1.        ]]


## **Predicted Rating**

In [47]:
user_index = 0
similarities = similarity_matrix[user_index]
similarities[user_index] = -1
similar_indices = np.argmax(similarities)
df1.loc[user_index, 'r5'] = df1.loc[similar_indices, 'r5']
print(df1)

  Customer  r1  r2  r3  r4   r5
0       C1   5   3   4   4  5.0
1       C2   3   1   2   3  3.0
2       C3   4   3   4   3  5.0
3       C4   3   3   1   5  4.0
4       C5   1   5   5   2  1.0
